<?php

namespace Database\Seeders;

use App\Domain\Order\Entities\Order;
use Illuminate\Database\Seeder;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        Order::insert([
            //unready
            [
                'car_name'      => 'Pajero',
                'number_plate'  => '熊谷 580 わ 1723',
                'car_color'         => 'ブラック系',
                'car_category'      => 'Rental',
                'car_condition'     => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/10/21',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'unready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '1',
                'store_destination'    => '3',
            ],
            [
                'car_name'      => 'CRV',
                'number_plate'  => '熊谷 580 わ 1722',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Service',
                'car_condition' => 'mati',
                'memo'          => 'rangka mobilnya masih bagus',
                'date'          => '2024/10/19',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'unready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '2',
                'store_destination'    => '1',
            ],
            [
                'car_name'      => 'Brio',
                'number_plate'  => '熊谷 580 わ 1723',
                'car_color'     => 'ブラック系',
                'car_category'  => 'New',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/08/19',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'unready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '3',
                'store_destination'    => '2',
            ],
            [
                'car_name'      => 'Civic',
                'number_plate'  => '熊谷 580 わ 1724',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Second',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/08/20',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'unready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '3',
                'store_destination'    => '2',
            ],
            [
                'car_name'      => 'HRV',
                'number_plate'  => '熊谷 580 わ 1725',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Second',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/08/20',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Test',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'unready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '3',
                'store_destination'    => '2',
            ],

            //ready
            [
                'car_name'      => 'Avanza',
                'number_plate'  => '熊谷 580 わ 1621',
                'car_color'         => 'ブラック系',
                'car_category'      => 'Rental',
                'car_condition'     => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/10/21',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'ready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '1',
                'store_destination'    => '3',
            ],
            [
                'car_name'      => 'Cayla',
                'number_plate'  => '熊谷 580 わ 1622',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Service',
                'car_condition' => 'mati',
                'memo'          => 'rangka mobilnya masih bagus',
                'date'          => '2024/10/19',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'ready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '2',
                'store_destination'    => '1',
            ],
            [
                'car_name'      => 'Xenia',
                'number_plate'  => '熊谷 580 わ 1623',
                'car_color'     => 'ブラック系',
                'car_category'  => 'New',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/08/19',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'ready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '3',
                'store_destination'    => '2',
            ],
            [
                'car_name'      => 'Sigra',
                'number_plate'  => '熊谷 580 わ 1624',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Second',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/08/20',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'ready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '3',
                'store_destination'    => '2',
            ],
            [
                'car_name'      => 'Rush',
                'number_plate'  => '熊谷 580 わ 1625',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Second',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/08/20',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Test',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'ready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '3',
                'store_destination'    => '2',
            ],

            //confirm
            [
                'car_name'      => 'Pajero',
                'number_plate'  => '熊谷 580 わ 1626',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Second',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/10/10',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Asep',
                'pic_2'         => 'Udin',
                'date_confirm'  => '2024/10/11',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '1',
                'driver_id'     => '3',
                'store_origin'    => '1',
                'store_destination'    => '2'
            ],
            [
                'car_name'      => 'Fortuner',
                'number_plate'  => '熊谷 580 わ 1726',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Second',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/10/10',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Asep',
                'pic_2'         => 'Udin',
                'date_confirm'  => '2024/10/11',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '2',
                'driver_id'     => '3',
                'store_origin'    => '1',
                'store_destination'    => '2'
            ],
            [
                'car_name'      => 'Brio',
                'number_plate'  => '熊谷 580 わ 1736',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Second',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/10/10',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Asep',
                'pic_2'         => 'Udin',
                'date_confirm'  => '2024/10/11',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '3',
                'driver_id'     => '3',
                'store_origin'    => '1',
                'store_destination'    => '2'
            ],
            [
                'car_name'      => 'Rush',
                'number_plate'  => '熊谷 580 わ 1751',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Second',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/10/10',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Asep',
                'pic_2'         => 'Udin',
                'date_confirm'  => '2024/10/11',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '3',
                'driver_id'     => '3',
                'store_origin'    => '1',
                'store_destination'    => '2'
            ],
            [
                'car_name'      => 'Honda Jazz',
                'number_plate'  => '熊谷 580 わ 1746',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Second',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/10/10',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Asep',
                'pic_2'         => 'Udin',
                'date_confirm'  => '2024/10/11',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '4',
                'driver_id'     => '3',
                'store_origin'    => '1',
                'store_destination'    => '2'
            ],
            [
                'car_name'      => 'Agya',
                'number_plate'  => '熊谷 580 わ 1627',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Second',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/10/11',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/10/12',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '1',
                'driver_id'     => '3',
                'store_origin'    => '2',
                'store_destination' => '3',
            ],
            [
                'car_name'      => 'CRV',
                'number_plate'  => '熊谷 580 わ 1628',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Second',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/10/20',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/10/25',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '1',
                'driver_id'     => '3',
                'store_origin'    => '4',
                'store_destination'    => '2',
            ],
            [
                'car_name'      => 'Brio',
                'number_plate'  => '熊谷 580 わ 1628',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Second',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/10/20',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/10/26',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '1',
                'driver_id'     => '4',
                'store_origin'    => '4',
                'store_destination'    => '2',
            ],
            //done
            [
                'car_name'      => 'Hyundai',
                'number_plate'  => '熊谷 580 わ 1629',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Second',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/08/20',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/10/23',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'done',
                'towing_id'     => '1',
                'driver_id'     => '4',
                'store_origin'  => '1',
                'store_destination'    => '2',
            ],
            [
                'car_name'      => 'Carry',
                'number_plate'  => '熊谷 580 わ 1630',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Second',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/08/20',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/10/25',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'done',
                'towing_id'     => '1',
                'driver_id'     => '3',
                'store_origin'  => '3',
                'store_destination'    => '2',
            ],
            [
                'car_name'      => 'Honda Jazz',
                'number_plate'  => '熊谷 580 わ 1631',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Second',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/08/20',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/10/21',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'done',
                'towing_id'     => '2',
                'driver_id'     => '3',
                'store_origin'  => '1',
                'store_destination'    => '2',
            ],
            [
                'car_name'      => 'Mobilio',
                'number_plate'  => '熊谷 580 わ 1831',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Second',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/08/20',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/10/21',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'done',
                'towing_id'     => '3',
                'driver_id'     => '3',
                'store_origin'  => '1',
                'store_destination'    => '2',
            ],
            [
                'car_name'      => 'Rush',
                'number_plate'  => '熊谷 580 わ 1931',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Second',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/08/20',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/10/21',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'done',
                'towing_id'     => '3',
                'driver_id'     => '3',
                'store_origin'  => '1',
                'store_destination'    => '2',
            ],
            [
                'car_name'      => 'Maung',
                'number_plate'  => '熊谷 580 わ 1931',
                'car_color'     => 'ブラック系',
                'car_category'  => 'Second',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/08/20',
                'time'          => '09:00 - 12:00',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/10/21',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'done',
                'towing_id'     => '4',
                'driver_id'     => '3',
                'store_origin'  => '1',
                'store_destination'    => '2',
            ],
        ]);
    }
}
