<?php

namespace Database\Seeders;

use App\Domain\Order\Entities\Order;
use Illuminate\Database\Seeder;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        Order::insert([
            //unready
            [
                'car_name'      => 'Pajero',
                'number_plate'  => '熊谷 580 わ 1723',
                'number_body'   => 'JAYKZE81SCJ154011',
                'car_color'     => 'ブラック系',
                'car_category'  => '新車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/16',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'unready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '1',
                'store_destination'    => '3',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'CRV',
                'number_plate'  => '熊谷 580 わ 1722',
                'number_body'   => 'JAYKZE81SCJ154012',
                'car_color'     => 'ブラック系',
                'car_category'  => '中古車',
                'car_condition' => 'mati',
                'memo'          => 'rangka mobilnya masih bagus',
                'date'          => '2024/12/16',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'unready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '2',
                'store_destination'    => '1',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Brio',
                'number_plate'  => '熊谷 580 わ 1723',
                'number_body'   => 'JAYKZE81SCJ154013',
                'car_color'     => 'ブラック系',
                'car_category'  => '車検車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/16',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'unready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '3',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Civic',
                'number_plate'  => '熊谷 580 わ 1724',
                'number_body'   => 'JAYKZE81SCJ154014',
                'car_color'     => 'ブラック系',
                'car_category'  => '修理車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/16',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'unready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '3',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'HRV',
                'number_plate'  => '熊谷 580 わ 1725',
                'number_body'   => 'JAYKZE81SCJ154015',
                'car_color'     => 'ブラック系',
                'car_category'  => '展示車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/16',
                'pic_1'         => 'Test',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'unready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '3',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],

            //ready
            [
                'car_name'      => 'Avanza',
                'number_plate'  => '熊谷 580 わ 1621',
                'number_body'   => 'JAYKZE81SCJ154016',
                'car_color'     => 'ブラック系',
                'car_category'  => 'レンタカー',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/16',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'ready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '1',
                'store_destination'    => '3',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Cayla',
                'number_plate'  => '熊谷 580 わ 1622',
                'number_body'   => 'JAYKZE81SCJ154017',
                'car_color'     => 'ブラック系',
                'car_category'  => '下取り',
                'car_condition' => 'mati',
                'memo'          => 'rangka mobilnya masih bagus',
                'date'          => '2024/12/16',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'ready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '2',
                'store_destination'    => '1',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Xenia',
                'number_plate'  => '熊谷 580 わ 1623',
                'number_body'   => 'JAYKZE81SCJ154018',
                'car_color'     => 'ブラック系',
                'car_category'  => '廃車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/16',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'ready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '3',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Sigra',
                'number_plate'  => '熊谷 580 わ 1624',
                'number_body'   => 'JAYKZE81SCJ154019',
                'car_color'     => 'ブラック系',
                'car_category'  => '新車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/15',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'ready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '3',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Rush',
                'number_plate'  => '熊谷 580 わ 1625',
                'number_body'   => 'JAYKZE81SCJ154020',
                'car_color'     => 'ブラック系',
                'car_category'  => '中古車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/15',
                'pic_1'         => 'Test',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'ready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '3',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],

            //confirm
            [
                'car_name'      => 'Pajero',
                'number_plate'  => '熊谷 580 わ 1626',
                'number_body'   => 'JAYKZE81SCJ154021',
                'car_color'     => 'ブラック系',
                'car_category'  => '車検車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/14',
                'pic_1'         => 'Asep',
                'pic_2'         => 'Udin',
                'date_confirm'  => '2024/12/15',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '1',
                'driver_id'     => '3',
                'store_origin'    => '1',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Fortuner',
                'number_plate'  => '熊谷 580 わ 1726',
                'number_body'   => 'JAYKZE81SCJ154022',
                'car_color'     => 'ブラック系',
                'car_category'  => '修理車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/13',
                'pic_1'         => 'Asep',
                'pic_2'         => 'Udin',
                'date_confirm'  => '2024/12/14',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '2',
                'driver_id'     => '3',
                'store_origin'    => '1',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Brio',
                'number_plate'  => '熊谷 580 わ 1736',
                'number_body'   => 'JAYKZE81SCJ154023',
                'car_color'     => 'ブラック系',
                'car_category'  => '展示車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/10',
                'pic_1'         => 'Asep',
                'pic_2'         => 'Udin',
                'date_confirm'  => '2024/12/11',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '3',
                'driver_id'     => '3',
                'store_origin'    => '1',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Rush',
                'number_plate'  => '熊谷 580 わ 1751',
                'number_body'   => 'JAYKZE81SCJ154024',
                'car_color'     => 'ブラック系',
                'car_category'  => '展示車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/10',
                'pic_1'         => 'Asep',
                'pic_2'         => 'Udin',
                'date_confirm'  => '2024/12/11',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '3',
                'driver_id'     => '3',
                'store_origin'    => '1',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Honda Jazz',
                'number_plate'  => '熊谷 580 わ 1746',
                'number_body'   => 'JAYKZE81SCJ154025',
                'car_color'     => 'ブラック系',
                'car_category'  => '展示車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/10',
                'pic_1'         => 'Asep',
                'pic_2'         => 'Udin',
                'date_confirm'  => '2024/12/11',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '4',
                'driver_id'     => '3',
                'store_origin'    => '1',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Agya',
                'number_plate'  => '熊谷 580 わ 1627',
                'number_body'   => 'JAYKZE81SCJ154026',
                'car_color'     => 'ブラック系',
                'car_category'  => '展示車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/11',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/12/13',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '1',
                'driver_id'     => '3',
                'store_origin'    => '2',
                'store_destination' => '3',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'CRV',
                'number_plate'  => '熊谷 580 わ 1628',
                'number_body'   => 'JAYKZE81SCJ154027',
                'car_color'     => 'ブラック系',
                'car_category'  => '展示車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/09',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/12/10',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '1',
                'driver_id'     => '3',
                'store_origin'    => '4',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Brio',
                'number_plate'  => '熊谷 580 わ 1628',
                'number_body'   => 'JAYKZE81SCJ154028',
                'car_color'     => 'ブラック系',
                'car_category'  => '展示車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/8',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/12/15',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '1',
                'driver_id'     => '4',
                'store_origin'    => '4',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            //done
            [
                'car_name'      => 'Hyundai',
                'number_plate'  => '熊谷 580 わ 1629',
                'number_body'   => 'JAYKZE81SCJ154029',
                'car_color'     => 'ブラック系',
                'car_category'  => '展示車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/12',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/12/13',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'done',
                'towing_id'     => '1',
                'driver_id'     => '4',
                'store_origin'  => '1',
                'store_destination'    => '2',
                'finished_at'   => '2024-12-15 15:57:43',
            ],
            [
                'car_name'      => 'Carry',
                'number_plate'  => '熊谷 580 わ 1630',
                'number_body'   => 'JAYKZE81SCJ154030',
                'car_color'     => 'ブラック系',
                'car_category'  => 'レンタカー',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/09',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/12/10',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'done',
                'towing_id'     => '1',
                'driver_id'     => '3',
                'store_origin'  => '3',
                'store_destination'    => '2',
                'finished_at'   => '2024-12-13 15:57:43',
            ],
            [
                'car_name'      => 'Honda Jazz',
                'number_plate'  => '熊谷 580 わ 1631',
                'number_body'   => 'JAYKZE81SCJ154031',
                'car_color'     => 'ブラック系',
                'car_category'  => 'レンタカー',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/12',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/12/13',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'done',
                'towing_id'     => '2',
                'driver_id'     => '3',
                'store_origin'  => '1',
                'store_destination'    => '2',
                'finished_at'   => '2024-12-13 15:57:43',
            ],
            [
                'car_name'      => 'Mobilio',
                'number_plate'  => '熊谷 580 わ 1831',
                'number_body'   => 'JAYKZE81SCJ154032',
                'car_color'     => 'ブラック系',
                'car_category'  => 'レンタカー',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/11',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/12/12',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'done',
                'towing_id'     => '3',
                'driver_id'     => '3',
                'store_origin'  => '1',
                'store_destination'    => '2',
                'finished_at'   => '2024-12-15 15:57:43',
            ],
            [
                'car_name'      => 'Rush',
                'number_plate'  => '熊谷 580 わ 1931',
                'number_body'   => 'JAYKZE81SCJ154033',
                'car_color'     => 'ブラック系',
                'car_category'  => 'レンタカー',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/12',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/12/11',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'done',
                'towing_id'     => '3',
                'driver_id'     => '3',
                'store_origin'  => '1',
                'store_destination'    => '2',
                'finished_at'   => '2024-12-13 15:57:43',
            ],
            [
                'car_name'      => 'Maung',
                'number_plate'  => '熊谷 580 わ 1931',
                'number_body'   => 'JAYKZE81SCJ154034',
                'car_color'     => 'ブラック系',
                'car_category'  => '下取り',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/07',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/12/10',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'done',
                'towing_id'     => '4',
                'driver_id'     => '3',
                'store_origin'  => '1',
                'store_destination'    => '2',
                'finished_at'   => '2024-12-11 15:57:43',
            ],

            //unready 2025
            [
                'car_name'      => 'Baic',
                'number_plate'  => '熊谷 570 わ 1723',
                'number_body'   => 'JAYKZE81SCJ154011',
                'car_color'     => 'ブラック系',
                'car_category'  => '新車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/30',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'unready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '1',
                'store_destination'    => '3',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Cherry',
                'number_plate'  => '熊谷 570 わ 1722',
                'number_body'   => 'JAYKZE81SCJ154012',
                'car_color'     => 'ブラック系',
                'car_category'  => '中古車',
                'car_condition' => 'mati',
                'memo'          => 'rangka mobilnya masih bagus',
                'date'          => '2024/12/30',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'unready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '2',
                'store_destination'    => '1',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Calya',
                'number_plate'  => '熊谷 570 わ 1723',
                'number_body'   => 'JAYKZE81SCJ154013',
                'car_color'     => 'ブラック系',
                'car_category'  => '車検車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/29',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'unready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '3',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Sigra',
                'number_plate'  => '熊谷 580 わ 1724',
                'number_body'   => 'JAYKZE81SCJ154014',
                'car_color'     => 'ブラック系',
                'car_category'  => '修理車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/29',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'unready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '3',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Jimmy',
                'number_plate'  => '熊谷 570 わ 1725',
                'number_body'   => 'JAYKZE81SCJ154015',
                'car_color'     => 'ブラック系',
                'car_category'  => '展示車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/28',
                'pic_1'         => 'Test',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'unready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '3',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            //ready 2025
            [
                'car_name'      => 'Baic',
                'number_plate'  => '熊谷 570 わ 1621',
                'number_body'   => 'JAYKZE81SCJ154016',
                'car_color'     => 'ブラック系',
                'car_category'  => 'レンタカー',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2025/01/01',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'ready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '1',
                'store_destination'    => '3',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Calya',
                'number_plate'  => '熊谷 570 わ 1622',
                'number_body'   => 'JAYKZE81SCJ154017',
                'car_color'     => 'ブラック系',
                'car_category'  => '下取り',
                'car_condition' => 'mati',
                'memo'          => 'rangka mobilnya masih bagus',
                'date'          => '2025/01/01',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'ready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '2',
                'store_destination'    => '1',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Cherry',
                'number_plate'  => '熊谷 570 わ 1623',
                'number_body'   => 'JAYKZE81SCJ154018',
                'car_color'     => 'ブラック系',
                'car_category'  => '廃車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2025/01/01',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'ready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '3',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Pino',
                'number_plate'  => '熊谷 570 わ 1624',
                'number_body'   => 'JAYKZE81SCJ154019',
                'car_color'     => 'ブラック系',
                'car_category'  => '新車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2025/01/02',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'ready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '3',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Jimmy',
                'number_plate'  => '熊谷 570 わ 1625',
                'number_body'   => 'JAYKZE81SCJ154020',
                'car_color'     => 'ブラック系',
                'car_category'  => '中古車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2025/01/03',
                'pic_1'         => 'Test',
                'pic_2'         => 'Anwar',
                'date_confirm'  => NULL,
                'time_confirm'  => NULL,
                'status'        => 'ready',
                'towing_id'     => NULL,
                'driver_id'     => NULL,
                'store_origin'    => '3',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            //confirm 2025
            [
                'car_name'      => 'Pajero',
                'number_plate'  => '熊谷 570 わ 1626',
                'number_body'   => 'JAYKZE81SCJ154021',
                'car_color'     => 'ブラック系',
                'car_category'  => '車検車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/30',
                'pic_1'         => 'Asep',
                'pic_2'         => 'Udin',
                'date_confirm'  => '2025/01/02',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '1',
                'driver_id'     => '3',
                'store_origin'    => '1',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Fortuner',
                'number_plate'  => '熊谷 570 わ 1726',
                'number_body'   => 'JAYKZE81SCJ154022',
                'car_color'     => 'ブラック系',
                'car_category'  => '修理車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/29',
                'pic_1'         => 'Asep',
                'pic_2'         => 'Udin',
                'date_confirm'  => '2025/01/01',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '2',
                'driver_id'     => '3',
                'store_origin'    => '1',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Brio',
                'number_plate'  => '熊谷 570 わ 1736',
                'number_body'   => 'JAYKZE81SCJ154023',
                'car_color'     => 'ブラック系',
                'car_category'  => '展示車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/31',
                'pic_1'         => 'Asep',
                'pic_2'         => 'Udin',
                'date_confirm'  => '2025/01/03',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '3',
                'driver_id'     => '3',
                'store_origin'    => '1',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Rush',
                'number_plate'  => '熊谷 570 わ 1751',
                'number_body'   => 'JAYKZE81SCJ154024',
                'car_color'     => 'ブラック系',
                'car_category'  => '展示車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/29',
                'pic_1'         => 'Asep',
                'pic_2'         => 'Udin',
                'date_confirm'  => '2025/01/03',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '3',
                'driver_id'     => '3',
                'store_origin'    => '1',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Honda Jazz',
                'number_plate'  => '熊谷 570 わ 1746',
                'number_body'   => 'JAYKZE81SCJ154025',
                'car_color'     => 'ブラック系',
                'car_category'  => '展示車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/30',
                'pic_1'         => 'Asep',
                'pic_2'         => 'Udin',
                'date_confirm'  => '2025/01/01',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '4',
                'driver_id'     => '3',
                'store_origin'    => '1',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Agya',
                'number_plate'  => '熊谷 570 わ 1627',
                'number_body'   => 'JAYKZE81SCJ154026',
                'car_color'     => 'ブラック系',
                'car_category'  => '展示車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/27',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2025/01/02',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '1',
                'driver_id'     => '3',
                'store_origin'    => '2',
                'store_destination' => '3',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'CRV',
                'number_plate'  => '熊谷 570 わ 1628',
                'number_body'   => 'JAYKZE81SCJ154027',
                'car_color'     => 'ブラック系',
                'car_category'  => '展示車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/26',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2025/01/03',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '1',
                'driver_id'     => '3',
                'store_origin'    => '4',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],
            [
                'car_name'      => 'Brio',
                'number_plate'  => '熊谷 570 わ 1628',
                'number_body'   => 'JAYKZE81SCJ154028',
                'car_color'     => 'ブラック系',
                'car_category'  => '展示車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/29',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2025/01/04',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'confirmed',
                'towing_id'     => '1',
                'driver_id'     => '4',
                'store_origin'    => '4',
                'store_destination'    => '2',
                'finished_at'     => NULL
            ],

            //done
            [
                'car_name'      => 'Hyundai',
                'number_plate'  => '熊谷 570 わ 1629',
                'number_body'   => 'JAYKZE81SCJ154029',
                'car_color'     => 'ブラック系',
                'car_category'  => '展示車',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/29',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2025/01/01',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'done',
                'towing_id'     => '1',
                'driver_id'     => '4',
                'store_origin'  => '1',
                'store_destination'    => '2',
                'finished_at'   => '2025-01-01 15:57:43',
            ],
            [
                'car_name'      => 'Carry',
                'number_plate'  => '熊谷 570 わ 1630',
                'number_body'   => 'JAYKZE81SCJ154030',
                'car_color'     => 'ブラック系',
                'car_category'  => 'レンタカー',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/30',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2025/01/02',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'done',
                'towing_id'     => '1',
                'driver_id'     => '3',
                'store_origin'  => '3',
                'store_destination'    => '2',
                'finished_at'   => '2025-01-02 15:57:43',
            ],
            [
                'car_name'      => 'Honda Jazz',
                'number_plate'  => '熊谷 570 わ 1631',
                'number_body'   => 'JAYKZE81SCJ154031',
                'car_color'     => 'ブラック系',
                'car_category'  => 'レンタカー',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/31',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2025/01/03',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'done',
                'towing_id'     => '2',
                'driver_id'     => '3',
                'store_origin'  => '1',
                'store_destination'    => '2',
                'finished_at'   => '2025-01-04 15:57:43',
            ],
            [
                'car_name'      => 'Mobilio',
                'number_plate'  => '熊谷 570 わ 1831',
                'number_body'   => 'JAYKZE81SCJ154032',
                'car_color'     => 'ブラック系',
                'car_category'  => 'レンタカー',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/31',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2025/01/03',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'done',
                'towing_id'     => '3',
                'driver_id'     => '3',
                'store_origin'  => '1',
                'store_destination'    => '2',
                'finished_at'   => '2025-01-03 15:57:43',
            ],
            [
                'car_name'      => 'Rush',
                'number_plate'  => '熊谷 570 わ 1931',
                'number_body'   => 'JAYKZE81SCJ154033',
                'car_color'     => 'ブラック系',
                'car_category'  => 'レンタカー',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/27',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2024/12/29',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'done',
                'towing_id'     => '3',
                'driver_id'     => '3',
                'store_origin'  => '1',
                'store_destination'    => '2',
                'finished_at'   => '2025-01-01 15:57:43',
            ],
            [
                'car_name'      => 'Maung',
                'number_plate'  => '熊谷 570 わ 1931',
                'number_body'   => 'JAYKZE81SCJ154034',
                'car_color'     => 'ブラック系',
                'car_category'  => '下取り',
                'car_condition' => 'hidup',
                'memo'          => 'kondisi mobilnya masih bagus',
                'date'          => '2024/12/27',
                'pic_1'         => 'Andre',
                'pic_2'         => 'Anwar',
                'date_confirm'  => '2025/01/03',
                'time_confirm'  => '09:00 - 12:00',
                'status'        => 'done',
                'towing_id'     => '4',
                'driver_id'     => '3',
                'store_origin'  => '1',
                'store_destination'    => '2',
                'finished_at'   => '2025-01-03 15:57:43',
            ],
        ]);
    }
}